modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "skyscobblemonutilsmod"
version = "1.0.0"
displayName = "Sky's Cobblemon Utils"
description = '''
A utility mod for Cobblemon that adds quality of life features including battle aggro protection and Pok√©ball restrictions.
'''
authors = "Sky"

[[dependencies.skyscobblemonutilsmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skyscobblemonutilsmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skyscobblemonutilsmod]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"
