modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mixins]]
config = "skyscobblemonutilsmod.mixins.json"

[[mods]]
modId = "skyscobblemonutilsmod"
version = "1.0.0"
displayName = "Sky's Cobblemon Utils"
description = '''
A utility mod for Cobblemon that adds quality of life features including battle aggro protection, daily-reset archaeology blocks, and Simple Voice Chat integration with a voice amplifier item.
'''
authors = "Sky"

[[dependencies.skyscobblemonutilsmod]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skyscobblemonutilsmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skyscobblemonutilsmod]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.skyscobblemonutilsmod]]
modId = "voicechat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
